---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nodeapplication"
  namespace: "default"
  labels:
    name: "nodejsapplication"
spec:
  replicas: 3
  selector:
    matchLabels:
      name: "nodejsapplication"
  template:
    metadata:
      labels:
        name: "nodejsapplication"
    spec:
      containers:
      - name: "github-mohammadkaif11-docker-sample-1"
        image: "gcr.io/shardings-c-362513/github_mohammadkaif11_docker_sample:$SHORT_SHA"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "nodeapplication-hpa-c184"
  namespace: "default"
  labels:
    name: "nodejsapplication"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "nodeapplication"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
