apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-webapp
  labels:
      app: node-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-webapp
  template:
    metadata:
      labels:
        app: node-webapp
    spec:
      containers:
      - name:docker-sample
        image:gcr.io/shardings-c-362513/restapi:v1
        ports:
          - containerPort: 3080 
