---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "sampleapplication"
  namespace: "default"
  labels:
    app: "sampleapplication"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "sampleapplication"
  template:
    metadata:
      labels:
        app: "sampleapplication"
    spec:
      containers:
      - name: "docker-sample-1"
        image: "gcr.io/shardings-c-362513/github.com/mohammadkaif11/docker_sample:$SHORT_SHA"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "sampleapplication-hpa-idfm"
  namespace: "default"
  labels:
    app: "sampleapplication"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "sampleapplication"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "sampleapplication-service"
  namespace: "default"
  labels:
    app: "sampleapplication"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "sampleapplication"
  type: "LoadBalancer"
  loadBalancerIP: ""
